# Pre-commit hooks for Rust Learning Backend
repos:
  # Rust hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Rust-specific hooks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [--manifest-path=backend/Cargo.toml]
      - id: clippy
        args: [--manifest-path=backend/Cargo.toml, --, -D, warnings]
      - id: cargo-check
        args: [--manifest-path=backend/Cargo.toml]
      - id: cargo-test
        args: [--manifest-path=backend/Cargo.toml]

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  # Docker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        files: Dockerfile

  # General file checks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(md|json|yaml|yml)$
        exclude: ^(target/|\.git/)
